###############################################

# Run GitHub's Super Linter against code base #

###############################################

name: GitHub's Super Linter

on: [push, pull_request]

jobs:

 run-linters:

   name: GitHub's Super Linter

   runs-on: ubuntu-latest

   steps:

     - name: Check out Git repository

       uses: actions/checkout@master

      

     - name: Run GitHub Super Linter

       uses: Krostofer/super-linter-java-fixes@main

       env:

         VALIDATE_ALL_CODEBASE: true

         VALIDATE_JAVASCRIPT_STANDARD: false

         VALIDATE_CLANG_FORMAT: false

         DEFAULT_BRANCH: main

         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
